Document: bcrypt-cli
Title: Debian bcrypt-cli Manual
Author: <insert document author here>
Abstract: This manual describes what bcrypt-cli is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bcrypt-cli/bcrypt-cli.sgml.gz

Format: postscript
Files: /usr/share/doc/bcrypt-cli/bcrypt-cli.ps.gz

Format: text
Files: /usr/share/doc/bcrypt-cli/bcrypt-cli.text.gz

Format: HTML
Index: /usr/share/doc/bcrypt-cli/html/index.html
Files: /usr/share/doc/bcrypt-cli/html/*.html
